### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DuchGhast** [spring-projects-experimental/spring-fu#362]

**Comment by jeffzoch** [comment]
its been a few weeks since the last commit - what suggests its dead?

**Comment by pull-vert** [comment]
Hi, I hope spring-fu will get back the initial motivation it had when it officially became a part of "spring-project-experimental" projects.

It seems like it is in stand-by mode for some months, without any major new features. Looks like big focus is on Graal support for now.

Here are 2 blog articles about spring-fu, and its roadmap :
* [2018/10/02 The evolution of Spring Fu](https://spring.io/blog/2018/10/02/the-evolution-of-spring-fu)
* [2020/05/28 Spring Fu 0.3.0 and beyond](https://spring.io/blog/2020/05/28/spring-fu-0-3-0-and-beyond)

Last one ended like this :

> In term of roadmap, the next 0.4.0 milestone will focus on:
> * Replacing the autoconfigure-adapter module by leveraging spring-init, an experimental project created by Dave Syer and Andy Clement which automatically converts Spring Boot auto-configurations to functional bean registration.
> * GraalVM native support without reflection configuration (depends on oracle/graal#2500)
> * Refined DSL extensibility
> * Scale-to-zero application sample with JaFu, GraalVM native and Knative
> * Leverage Spring Framework 5.3 M1 to remove by default XML and SpEL support
> * Spring Security support via Spring Security 5.3 official Kotlin DSL
> 
> As usual, feedback is welcome. Be aware that we have for now mainly a focus on getting the right software design and APIs rather than an extensive coverage of more features.

I hope these goals are in active progress, starting with 'Replacing the autoconfigure-adapter module by leveraging spring-init' that would bring full spring-boot support without the need of writing some code for autoconfigure-adapter anymore !

**Comment by sdeleuze** [comment]
Hi, sorry for not sharing feedback, I was deep in [Spring Native beta release](https://spring.io/blog/2021/03/11/announcing-spring-native-beta) and indeed Spring Native takes a lot of my bandwidth these days.

Those 2 topics are not unrelated since Spring Native beta has introduced Spring AOT which should in 0.11 allow to convert automatically `@Configuration` to functional configuration, see spring-projects-experimental/spring-native#386 related issue. This will allow us to replace `autoconfigure-adapter` module by something more maitainable.

I am going to release a [0.4.4](https://github.com/spring-projects-experimental/spring-fu/milestone/21) with current changes on `master` tomorrow.

**Comment by pull-vert** [comment]
Thanks a lot for this feedback @sdeleuze 

If spring-fu will soon depend on Spring AOT (which should in 0.11 allow to convert automatically @Configuration to functional configuration), instead of autoconfigure-adapter, does this meen that spring-fu will then require and force to use GraalVM and Spring Native ?

**Comment by sdeleuze** [comment]
No Spring AOT will evolve to not be tied to Spring Native, and will be moved in another repository later.

**Comment by pull-vert** [comment]
Nice, thanks again @sdeleuze
