### ISSUE TITLE
[question] is Spring Fu production ready?

### ISSUE THREAD

**Issue by ljtfreitas** [spring-projects-experimental/spring-fu#382]
Hi all :wave: , just a quick question,

We are starting some projects with spring boot/kotlin, and I would prefer to walk through a programmatic, functional approach. So...

is `spring-fu` production ready?

If it doesn't, does the current Kotlin support for programmatic configuration in spring framework/spring boot have the same features from `kofu`?

Thanks in advance.

**Comment by sdeleuze** [comment]
Spring Fu is not production ready, that's why it still lives in https://github.com/spring-projects-experimental, but Spring Framework/Boot is where indeed most of its features (bean DSL, web DSL) are available, "just" the configuration DSL is missing so you will have to use annotations or `ApplicationContextInitializer`.
